[[configuring-topics]]
= Configuring Topics

* 👀if you define a `KafkaAdmin` bean | your application context -> it can -- automatically add -- topics | broker 👀
    ** 👀if you use Spring Boot -> automatically a `KafkaAdmin` bean is automatically registered 👀
    ** way to define these beans
        *** add a `NewTopic` `@Bean` / EACH topic | application context
        *** | spring-kafka v2.3+, -- via -- `TopicBuilder`
            **** _Example:_

[tabs]
======
Java::
+
[source, java, indent=0, role="primary"]
----
include::{java-examples}/topics/Config.java[tag=topicBeans]
----

Kotlin::
+
[source, kotlin, indent=0, role="secondary"]
----
include::{kotlin-examples}/topics/Config.kt[tag=topicBeans]
----
======

* | spring-kafka v2.6+ & Kafka Broker v2.4.0+ -> you can (check https://cwiki.apache.org/confluence/display/KAFKA/KIP-464%3A+Defaults+for+AdminClient%23createTopic[KIP-464]) omit
    ** `partitions()`
        *** -> broker defaults will be applied
    ** `replicas()`
        *** broker defaults will be applied

[tabs]
======
Java::
+
[source, java, indent=0, role="primary"]
----
include::{java-examples}/topics/Config.java[tag=brokerProps]
----

Kotlin::
+
[source, kotlin, indent=0, role="secondary"]
----
include::{kotlin-examples}/topics/Config.kt[tag=brokerProps]
----
======

* | spring-kafka v2.7+
    ** you can declare multiple `NewTopic`+++S+++ | 1! `KafkaAdmin.NewTopics` bean definition
+
[tabs]
======
Java::
+
[source, java, indent=0, role="primary"]
----
include::{java-examples}/topics/Config.java[tag=newTopicsBean]
----

Kotlin::
+
[source, kotlin, indent=0, role="secondary"]
----
include::{kotlin-examples}/topics/Config.kt[tag=newTopicsBean]
----
======

    ** `KafkaAdmin` 's methods
        *** | runtime
            **** `createOrModifyTopics`
            **** `describeTopics`
        *** alternative
            **** use `AdminClient`
+
[source, java]
----
@Autowired
private KafkaAdmin admin;

...

    AdminClient client = AdminClient.create(admin.getConfigurationProperties());
    ...
    client.close();
----

* if the broker is NOT available ->
    ** message is logged
    ** behavior
        *** by default, context STILL continues to load
        *** if you want to consider as fatal == context fails to initialize -> set `KafkaAdmin.fatalIfBrokerNotAvailable=true`
    ** if you want to try again later -> programmatically invoke `KafkaAdmin.initialize()`

* | spring-kafka v1.0.0+
    ** if an existing topic's partitions < `NewTopic.numPartitions` -> KafkaAdmin increases the # of partitions

* | spring-kafka v2.9.10+, v3.0.9+
    ** you -- can provide a -- `Predicate<NewTopic>`
        *** uses
            **** determine whether a particular `NewTopic` bean -- should be considered for --
                ***** creation or
                ***** modification
        *** use cases
            **** if you have multiple `KafkaAdmin` instances / point to different clusters & you wish to select those topics / -- should be -- created OR modified / EACH admin
+
[source, java]
----
admin.setCreateOrModifyTopic(nt -> !nt.name().equals("dontCreateThisOne"));
----

