[[connecting]]
= Connecting to Kafka

* `KafkaAdmin`
    ** check xref:kafka/configuring-topics.adoc[Configuring Topics]
* `ProducerFactory`
    ** check xref:kafka/sending-messages.adoc[Sending Messages]
* `ConsumerFactory`
    ** check xref:kafka/receiving-messages.adoc[Receiving Messages]

* | spring-kafka v2.5+
    ** `KafkaAdmin`, `ProducerFactory` & `ConsumerFactory` -- extends -- `KafkaResourceFactory`
        *** -> allows
            **** 👀changing the bootstrap servers | runtime -- via --   `setBootstrapServersSupplier(() +++->+++ ...)` 👀
                ***** == add a `Supplier<String>` | their configuration
                ***** done / ALL NEW connections

* Consumers & Producers are generally long-lived
    ** if you want to close existing
        *** Producers -> `DefaultKafkaProducerFactory.reset()`
        *** Consumers -> `KafkaListenerEndpointRegistry.stop()` +  `KafkaListenerEndpointRegistry.start()`| any other listener container beans

* `ABSwitchCluster`
    ** provided -- by the -- framework
    ** supports
        *** 2 sets of bootstrap servers
            **** one is active | ANY time
            **** if you want to switch &
                ***** | producer factory -> `primary()` or `secondary()` + `reset()`
                ***** | consumer -> `stop()` + `start()`
                ***** use `@KafkaListener`+++s+++ ->  `KafkaListenerEndpointRegistry.stop()` + `KafkaListenerEndpointRegistry.start()`
    ** steps
        *** configure it
        *** add it -- via `setBootstrapServersSupplier()` -- |
            *** producer factory
            *** consumer factory
            *** `KafkaAdmin`

[[factory-listeners]]
== Factory Listeners

* | spring-kafka v2.5+
    ** `DefaultKafkaProducerFactory` and `DefaultKafkaConsumerFactory` -- can be configured with a -- `Listener` /
        *** if producer or consumer is created or closed -> receive notifications
        *** 👀`id` == `client-id.beanName` 👀
            **** `client-id`  -- obtained from the -- `metrics()` | after creation
        *** uses
            **** if a new client is
                ***** created -> create & bind a Micrometer `KafkaClientMetrics` instance
                ***** closed -> close the Micrometer `KafkaClientMetrics` instance
            **** see xref:kafka/micrometer.adoc#micrometer-native[Micrometer Native Metrics]

.Producer Factory Listener
[source, java]
----
interface Listener<K, V> {

    default void producerAdded(String id, Producer<K, V> producer) {
    }

    default void producerRemoved(String id, Producer<K, V> producer) {
    }

}
----

.Consumer Factory Listener
[source, java]
----
interface Listener<K, V> {

    default void consumerAdded(String id, Consumer<K, V> consumer) {
    }

    default void consumerRemoved(String id, Consumer<K, V> consumer) {
    }

}
----


[[default-client-id-prefixes]]
== Default client ID prefixes

* | spring-kafka v3.2+
    ** if Spring Boot applications / define an application name -- via -- `spring.application.name` -> 👀`spring.application.name` -- is used as -- default prefix for auto-generated client IDs | client / types 👀
        *** consumer clients / do NOT use a consumer group
        *** producer clients
        *** admin clients

.Example: client ids / Spring Boot application / use `spring.application.name=myapp`
[%autowidth]
|===
|Client Type |Without application name |With application name

|consumer without consumer group
|consumer-null-1
|myapp-consumer-1

|consumer with consumer group "mygroup"
|consumer-mygroup-1
|consumer-mygroup-1

|producer
|producer-1
|myapp-producer-1

|admin
|adminclient-1
|myapp-admin-1
|===

