[[micrometer]]
= Monitoring

[[monitoring-listener-performance]]
== Monitoring Listener Performance

Starting with version 2.3, the listener container will automatically create and update Micrometer `Timer`+++s+++ for the listener, if `Micrometer` is detected on the classpath, and a single `MeterRegistry` is present in the application context.
The timers can be disabled by setting the `ContainerProperty`+++'+++s `micrometerEnabled` to `false`.

Two timers are maintained - one for successful calls to the listener and one for failures.

The timers are named `spring.kafka.listener` and have the following tags:

* `name` : (container bean name)
* `result` : `success` or `failure`
* `exception` : `none` or `ListenerExecutionFailedException`

You can add additional tags using the `ContainerProperties`+++'+++s `micrometerTags` property.

Starting with versions 2.9.8, 3.0.6, you can provide a function in `ContainerProperties`+++'+++s `micrometerTagsProvider`; the function receives the `ConsumerRecord<?, ?>` and returns tags which can be based on that record, and merged with any static tags in `micrometerTags`.

NOTE: With the concurrent container, timers are created for each thread and the `name` tag is suffixed with `-n` where n is `0` to `concurrency-1`.

[[monitoring-kafkatemplate-performance]]
== Monitoring KafkaTemplate Performance

Starting with version 2.5, the template will automatically create and update Micrometer `Timer`+++s+++ for send operations, if `Micrometer` is detected on the classpath, and a single `MeterRegistry` is present in the application context.
The timers can be disabled by setting the template's `micrometerEnabled` property to `false`.

Two timers are maintained - one for successful calls to the listener and one for failures.

The timers are named `spring.kafka.template` and have the following tags:

* `name` : (template bean name)
* `result` : `success` or `failure`
* `exception` : `none` or the exception class name for failures

You can add additional tags using the template's `micrometerTags` property.

Starting with versions 2.9.8, 3.0.6, you can provide a `KafkaTemplate.setMicrometerTagsProvider(Function<ProducerRecord<?, ?>, Map<String, String>>)` property; the function receives the `ProducerRecord<?, ?>` and returns tags which can be based on that record, and merged with any static tags in `micrometerTags`.

[[micrometer-native]]
== Micrometer Native Metrics

Starting with version 2.5, the framework provides xref:kafka/connecting.adoc#factory-listeners[Factory Listeners] to manage a Micrometer `KafkaClientMetrics` instance whenever producers and consumers are created and closed.

To enable this feature, simply add the listeners to your producer and consumer factories:

[source, java]
----
@Bean
public ConsumerFactory<String, String> myConsumerFactory() {
    Map<String, Object> configs = consumerConfigs();
    ...
    DefaultKafkaConsumerFactory<String, String> cf = new DefaultKafkaConsumerFactory<>(configs);
    ...
    cf.addListener(new MicrometerConsumerListener<String, String>(meterRegistry(),
            Collections.singletonList(new ImmutableTag("customTag", "customTagValue"))));
    ...
    return cf;
}

@Bean
public ProducerFactory<String, String> myProducerFactory() {
    Map<String, Object> configs = producerConfigs();
    configs.put(ProducerConfig.CLIENT_ID_CONFIG, "myClientId");
    ...
    DefaultKafkaProducerFactory<String, String> pf = new DefaultKafkaProducerFactory<>(configs);
    ...
    pf.addListener(new MicrometerProducerListener<String, String>(meterRegistry(),
            Collections.singletonList(new ImmutableTag("customTag", "customTagValue"))));
    ...
    return pf;
}
----

The consumer/producer `id` passed to the listener is added to the meter's tags with tag name `spring.id`.

.An example of obtaining one of the Kafka metrics
[source, java]
----
double count = this.meterRegistry.get("kafka.producer.node.incoming.byte.total")
                .tag("customTag", "customTagValue")
                .tag("spring.id", "myProducerFactory.myClientId-1")
                .functionCounter()
                .count();
----

A similar listener is provided for the `StreamsBuilderFactoryBean` - see xref:streams.adoc#streams-micrometer[KafkaStreams Micrometer Support].

[[observation]]
== Micrometer Observation

* requirements
    ** spring-kafka v3.0+
    ** set
        *** `KafkaTemplate.observationEnabled=true`
        *** `ContainerProperties.observationEnabled=true`
        *** -> disable xref:kafka/micrometer.adoc[Micrometer Timers]
            **** Reason: 🧠 timers -- will NOW be managed with -- EACH observation 🧠
* uses
    ** observation for
        *** `KafkaTemplate`
        *** listener containers
* NOT support batch listener
    ** Reason: 🧠 it would enable Micrometer Timers 🧠
* check https://micrometer.io/docs/tracing[Micrometer Tracing]
* 👀if you want to add tags | timers/traces -> configure a custom 👀
    ** `KafkaTemplateObservationConvention` | template or
    ** `KafkaListenerObservationConvention` | listener container
* default implementations -- add -- the tags
    ** `bean.name` / template observations
    ** `listener.id` / containers
* ways to provide completely new implementations
    ** subclass of
        *** `DefaultKafkaTemplateObservationConvention` or
        *** `DefaultKafkaListenerObservationConvention`
* xref:appendix/micrometer.adoc#observation-gen[default observations / are recorded]

* | spring-kafka v3.0.6+
    ** based on information | consumer or producer records -> you can add dynamic tags
        *** |
            **** timers
            **** traces
        *** -- via adding -- custom
            **** `KafkaListenerObservationConvention` | listener container properties and/or
            **** `KafkaTemplateObservationConvention` | `KafkaTemplate`
        *** `record` property -- contains the -- `ConsumerRecord` or `ProducerRecord`
* |sender & receiver contexts,
    ** `remoteServiceName` properties = Kafka `clusterId` property
        *** Kafka `clusterId` property -- is retrieved by a -- `KafkaAdmin`
            **** if you can NOT retrieve the `clusterId` (_Example:_ lack of permissions) & spring-kafka v3.1+ -> you can
                ***** set a manual `clusterId` | `KafkaAdmin`
                ***** inject it |
                    ****** `KafkaTemplate` s
                    ****** listener containers
            **** if `clusterId=null` (default) -> `KafkaAdmin` -- will invoke the -- `describeCluster` admin operation /  -- retrieve it from the -- broker
