== Sample 1

* goal
    ** simple producer & consumer

* producer
    ** sends `Foo1` objects type /
        *** `Foo1` objects type == `foo` field
    ** uses a `JsonSerializer`
* consumer
    ** receives `Foo2` objects type /
        *** `Foo2` objects type == `foo` field
    ** uses a `ByteArrayDeserializer`
        *** \+ `JsonMessageConverter`

### How to run locally?
* | this path
    ** `mvn wrapper:wrapper`
        *** generate Maven wrappers
* | "scripts/"
    ** `docker compose up`
* | this path
    ** `./mvnw clean install` OR `./mvnw spring-boot:run`
        *** Problems:
            **** Problem1: "Failed to fetch ... apache-maven/3.9.9/apache-maven-3.9.9-bin.zip"
                ***** Solution: | ".mvn/maven-wrapper.properties", use default `distributionUrl`
* trigger
    ** `$ curl -X POST http://localhost:8080/send/foo/bar`
        *** check the console' message
+
`2018-11-05 10:03:40.216  INFO 39766 --- [ fooGroup-0-C-1] com.example.Application                  : Received: Foo2 [foo=bar]`
        *** TODO: consumer is configured with a `SeekToCurrentErrorHandler` which replays failed messages up to 2 times, each after a 1 second delay and, after retries are exhausted, sends a bad message to a dead-letter topic.
    ** `$ curl -X POST http://localhost:8080/send/foo/fail`
        *** second `@KafkaListener` -- consumes , from the message, the -- raw JSON
        *** check the console' message
+
[source, bash]
----

2018-11-05 10:12:32.552  INFO 41635 --- [ fooGroup-0-C-1] com.example.Application                  : Received: Foo2 [foo=fail]
2018-11-05 10:12:32.561 ERROR 41635 --- [ fooGroup-0-C-1] essageListenerContainer$ListenerConsumer : Error handler threw an exception
...
2018-11-05 10:12:33.033  INFO 41635 --- [ fooGroup-0-C-1] com.example.Application                  : Received: Foo2 [foo=fail]
2018-11-05 10:12:33.033 ERROR 41635 --- [ fooGroup-0-C-1] essageListenerContainer$ListenerConsumer : Error handler threw an exception
...
2018-11-05 10:12:33.537  INFO 41635 --- [ fooGroup-0-C-1] com.example.Application                  : Received: Foo2 [foo=fail]
2018-11-05 10:12:43.359  INFO 41635 --- [ dltGroup-0-C-1] com.example.Application                  : Received from DLT: {"foo":"fail"}
----