[[back-off-delay-precision]]
= Back Off Delay Precision
:page-section-summary-toc: 1

[[overview-and-guarantees]]
== Overview and Guarantees

* ALL message processing & backing off -- is handled by the -- consumer thread
    ** 👀backing off == delay or pause | BEFORE retrying a failed operation 👀
    ** -> delay precision is guaranteed | best-effort basis
* if one message's processing takes longer > next message's back off period for that consumer -> next message's delay > expected
    ** ALTHOUGH, it's short delays (<=1s) -> 👀maintenance work / made by the thread (_Example:_ committing offsets) -- may delay the -- message processing execution 👀
    ** & retry topic's consumer is handling >1 partition -> precision can ALSO be affected
        *** Reason: 🧠requirements by consumer, to make timing adjustments 🧠
            **** waking up the consumer -- from -- polling &
                ***** == poll operation completes
            **** having full pollTimeouts
    ** & consumers handling 1! partition -> message's processing should occur approximately (NEVER before) | its exact time for MOST situations
