[[dlt-strategies]]
= DLT Strategies

* SOME DLT strategies -- are provided by the -- framework
    ** method -- for -- DLT processing
    ** default logging method
    ** NO DLT
    ** if DLT processing fails -> choose what to do

[[dlt-processing-method]]
== DLT Processing Method

* things / you can specify
    ** method / process the DLT for the topic
    ** behavior if that processing fails

* steps
    ** 👀set DLT handler method 👀
        *** ways
            **** use the `@DltHandler` annotation | a method of the class / has the `@RetryableTopic`
                ***** -> ⚠️ used by ALL the `@RetryableTopic` annotated methods | that class ⚠️
                ***** _Example:_
+
[source, java]
----
@RetryableTopic
@KafkaListener(topics = "my-annotated-topic")
public void processMessage(MyPojo message) {
    // ... message processing
}

@DltHandler
public void processMessage(MyPojo message) {
    // ... message processing, persistence, etc
}
----
            **** `RetryTopicConfigurationBuilder.dltHandlerMethod(String beanName, String methodNameWhichProcessDLTMessages)`
                ***** _Example:_
+
[source, java]
----
@Bean
public RetryTopicConfiguration myRetryTopic(KafkaTemplate<Integer, MyPojo> template) {
    return RetryTopicConfigurationBuilder
            .newInstance()
            .dltHandlerMethod("myCustomDltProcessor", "processDltMessage")
            .create(template);
}

@Component
public class MyCustomDltProcessor {

    private final MyDependency myDependency;

    public MyCustomDltProcessor(MyDependency myDependency) {
        this.myDependency = myDependency;
    }

    public void processDltMessage(MyPojo message) {
        // ... message processing, persistence, etc
    }
}
----
        *** 👀if NO DLT handler is set -> default `RetryTopicConfigurer.LoggingDltListenerHandlerMethod` is used 👀

* | v2.8,
    ** 👀if you do NOT want to consume from the DLT at all (NOR the default handler) OR to defer consumption & 👀
        *** you use the `@RetryableTopic` -> set `autoStartDltHandler=false`
        *** you use the `RetryTopicConfigurationBuilder` -> se `autoStartDltHandler(false)`
        *** you want LATER start the DLT handler -> use `KafkaListenerEndpointRegistry`

[[dlt-failure-behavior]]
== DLT Failure Behavior

* AVAILABLE DLT Failure behaviors
    ** `ALWAYS_RETRY_ON_ERROR`
        *** record -- is forwarded back to the -- DLT topic -> NOT block OTHER DLT records' processing
        *** 👀default behavior 👀
        *** | v2.8.3,
            **** ⚠️if the record causes a fatal exception to be thrown (_Example:_ `DeserializationException`) -> record -- is NOT routed back to the --  DLT ⚠️
                ***** fatal exception
                    ****** by default, are
                        ******* `DeserializationException`
                        ******* `MessageConversionException`
                        ******* `ConversionException`
                        ******* `MethodArgumentResolutionException`
                        ******* `NoSuchMethodException`
                        ******* `ClassCastException`
                    ****** you can customize the list -- via -- `DestinationTopicResolver` bean
                        ******* see xref:retrytopic/features.adoc#retry-topic-ex-classifier[Exception Classifier]
** `FAIL_ON_ERROR`
        *** consumer ends the execution / NOT forward the message
        *** _Example:_
            **** via `@RetryableTopic`
+
[source,java]
----

@RetryableTopic(dltProcessingFailureStrategy =
            DltStrategy.FAIL_ON_ERROR)
@KafkaListener(topics = "my-annotated-topic")
public void processMessage(MyPojo message) {
    // ... message processing
}
----
            **** via `@RetryTopicConfiguration`
[source, java]
----
@Bean
public RetryTopicConfiguration myRetryTopic(KafkaTemplate<Integer, MyPojo> template) {
    return RetryTopicConfigurationBuilder
            .newInstance()
            .dltHandlerMethod("myCustomDltProcessor", "processDltMessage")
            .doNotRetryOnDltFailure()
            .create(template);
}
----

[[configuring-no-dlt]]
== Configuring No DLT

* == NOT configure a DLT | topic
    ** -> if retrials are exhausted -> processing ends
    ** _Example:_
        *** via `@RetryableTopic`
+
[source, java]
----

@RetryableTopic(dltProcessingFailureStrategy =
            DltStrategy.NO_DLT)
@KafkaListener(topics = "my-annotated-topic")
public void processMessage(MyPojo message) {
    // ... message processing
}
----
        *** via `RetryTopicConfigurationBuilder`
+
[source, java]
----
@Bean
public RetryTopicConfiguration myRetryTopic(KafkaTemplate<Integer, MyPojo> template) {
    return RetryTopicConfigurationBuilder
            .newInstance()
            .doNotConfigureDlt()
            .create(template);
}
----
