[[features]]
= Features

* Most of the features -- are available both for the --
    ** `@RetryableTopic`
    ** `RetryTopicConfiguration` beans

[[backoff-configuration]]
== BackOff Configuration

* ðŸ‘€-- relies on the -- `Spring Retry` project's `BackOffPolicy` interface ðŸ‘€/ includes
    ** Fixed Back Off
        *** `FixedBackOffPolicy`
        *** default one -- `FixedBackOffPolicy` / 3 maximum retries & 1000ms intervals
        *** _Example:_
+
[source, java]
----
@RetryableTopic(attempts = 5,
    backoff = @Backoff(delay = 1000, multiplier = 2, maxDelay = 5000))
@KafkaListener(topics = "my-annotated-topic")
public void processMessage(MyPojo message) {
    // ... message processing
}
----
+
[source, java]
----
@Bean
public RetryTopicConfiguration myRetryTopic(KafkaTemplate<String, MyPojo> template) {
    return RetryTopicConfigurationBuilder
            .newInstance()
            .fixedBackOff(3_000)
            .maxAttempts(4)
            .create(template);
}
----
    ** Exponential Back Off
        *** `ExponentialBackOffPolicy`
        *** 30-second default maximum delay
            **** if you need other -> adjust `maxDelay`
    ** Random Exponential Back Off
    ** Uniform Random Back Off
    ** No Back Off
    ** Custom Back Off



* `SleepingBackOffPolicy`
    ** if you want to customize -> implement it
+
[source, java]
----
@Bean
public RetryTopicConfiguration myRetryTopic(KafkaTemplate<String, MyPojo> template) {
    return RetryTopicConfigurationBuilder
            .newInstance()
            .customBackoff(new MyCustomBackOffPolicy()) // MyCustomBackOffPolicy        implementation of SleepingBackOffPolicy
            .maxAttempts(5)
            .create(template);
}
----

* ðŸ‘€first attempt counts against `maxAttempts`ðŸ‘€
    ** _Example:_ if `maxAttempts=4` -> there'll be the original attempt + 3 retries

[[global-timeout]]
== Global Timeout | retrying processes

* if that time is reached -> next time the consumer -- throws an -- exception /
    ** message -- goes to the -- DLT, or
    ** if NO DLT is available -> ends the processing
* _Example:_
[source, java]
----
@RetryableTopic(backoff = @Backoff(2_000), timeout = 5_000)     // timeout  == global timeout
@KafkaListener(topics = "my-annotated-topic")
public void processMessage(MyPojo message) {
    // ... message processing
}
----

[source, java]
----
@Bean
public RetryTopicConfiguration myRetryTopic(KafkaTemplate<String, MyPojo> template) {
    return RetryTopicConfigurationBuilder
            .newInstance()
            .fixedBackOff(2_000)
            .timeoutAfter(5_000)
            .create(template);
}
----

* by default, NO timeout == set `timeout=-1`

[[retry-topic-ex-classifier]]
== Exception Classifier

* allow
    ** specifying which exceptions will be retried or NOT

* _Example:_
[source, java]
----
@RetryableTopic(include = {MyRetryException.class, MyOtherRetryException.class}, traversingCauses = true)
@KafkaListener(topics = "my-annotated-topic")
public void processMessage(MyPojo message) {
    throw new RuntimeException(new MyRetryException()); // will retry
}
----

[source, java]
----
@Bean
public RetryTopicConfiguration myRetryTopic(KafkaTemplate<String, MyOtherPojo> template) {
    return RetryTopicConfigurationBuilder
            .newInstance()
            .notRetryOn(MyDontRetryException.class)
            .create(template);
}
----

* ðŸ‘€by default, retry ALL exceptions & NOT traversing causes ðŸ‘€

* | v2.8.3
    ** âš ï¸EXIST global list of fatal exceptions / record -- will be sent, WITHOUT any retries, to the -- DLT âš ï¸
        *** see xref:kafka/annotation-error-handling.adoc#default-eh[DefaultErrorHandler]
        *** if you want to customize (== add or remove exceptions | this list) -> override the `configureNonBlockingRetries` method | `@Configuration` class / extends `RetryTopicConfigurationSupport`
            **** see xref:retrytopic/retry-config.adoc#retry-topic-global-settings[Configuring Global Settings and Features]

[[include-and-exclude-topics]]
== Include and Exclude Topics

* `RetryTopicConfiguration` bean
    ** ðŸ‘€by default, ALL topics are included ðŸ‘€
    ** `.includeTopic(String topic)` & `.includeTopics(Collection<String> topics)`
        *** specify topics / will be handled
    ** `.excludeTopic(String topic)` & `.excludeTopics(Collection<String> topics)`
        *** specify topics / will NOT be handled
    ** _Example:_
+
[source, java]
----
@Bean
public RetryTopicConfiguration myRetryTopic(KafkaTemplate<Integer, MyPojo> template) {
    return RetryTopicConfigurationBuilder
            .newInstance()
            .includeTopics(List.of("my-included-topic", "my-other-included-topic"))
            .create(template);
}

@Bean
public RetryTopicConfiguration myOtherRetryTopic(KafkaTemplate<Integer, MyPojo> template) {
    return RetryTopicConfigurationBuilder
            .newInstance()
            .excludeTopic("my-excluded-topic")
            .create(template);
}
----

[[topics-autocreation]]
== Topics AutoCreation

* ðŸ’¡framework -- will auto create, via `NewTopic` beans / consumed by the `KafkaAdmin` bean, -- the required topics ðŸ’¡
    ** you can
        *** specify the
            **** # of partitions
                ***** 1, by default
            **** replication factor of the topics
                ***** | spring-kafka v3.0+, the default is `-1`
                    ****** == broker default
                ***** | broker v2.4- -> needed to specify it
        *** turn this feature off
    ** ðŸ‘€if you're NOT using Spring Boot -> you'll have to provide a `KafkaAdmin` bean ðŸ‘€

[source, java]
----
// 1. @RetryableTopic
// 1.1 specify partitions and # of replicas
@RetryableTopic(numPartitions = 2, replicationFactor = 3)
@KafkaListener(topics = "my-annotated-topic")
public void processMessage(MyPojo message) {
    // ... message processing
}

// 1.2 turn auto creation of topics, off
@RetryableTopic(autoCreateTopics = false)
@KafkaListener(topics = "my-annotated-topic")
public void processMessage(MyPojo message) {
    // ... message processing
}
----
[source, java]
----
// 2. RetryTopicConfiguration bean
// 2.1 specify partitions and # of replicas
@Bean
public RetryTopicConfiguration myRetryTopic(KafkaTemplate<Integer, MyPojo> template) {
    return RetryTopicConfigurationBuilder
            .newInstance()
            .autoCreateTopicsWith(2, 3)
            .create(template);
}

// 2.2 turn auto creation of topics, off
@Bean
public RetryTopicConfiguration myOtherRetryTopic(KafkaTemplate<Integer, MyPojo> template) {
    return RetryTopicConfigurationBuilder
            .newInstance()
            .doNotAutoCreateRetryTopics()
            .create(template);
}
----

[[retry-headers]]
== Failure Header Management

* `DeadLetterPublishingRecoverer`
    ** allows
        *** managing failure headers (original headers & exception headers)
            **** _Example:_ append or replace the headers
    ** by default,
        *** `appendOriginalHeaders=false`
            **** ðŸ‘€-> ONLY the FIRST "original" and LAST exception headers are retained ðŸ‘€
                ***** Reason: ðŸ§  avoid creating excessively large messages | MANY retry steps are involved ðŸ§ 
        *** `stripPreviousExceptionHeaders` == default / used by the `DeadLetterPublishingRecover`
    ** if you want to customize -> override the `configureCustomizers` method | `@Configuration` class / extends `RetryTopicConfigurationSupport`
        *** _Example:_
+
[source, java]
----
@Override
protected void configureCustomizers(CustomizersConfigurer customizersConfigurer) {
    customizersConfigurer.customizeDeadLetterPublishingRecoverer(dlpr -> {
        dlpr.setAppendOriginalHeaders(true);
        dlpr.setStripPreviousExceptionHeaders(false);
    });
}
----
    ** if you want to add custom headers
        *** | v2.8.4,  -> `factory.setHeadersFunction((rec, ex) +++->+++ { +++...+++ })`
        *** | v2.9.5, if the `Headers` / returned by the function contains a header of type `DeadLetterPublishingRecoverer.SingleRecordHeader` ->
            **** ANY existing header's value will be removed
            **** ONLY the NEW single value will remain
    ** see
        *** xref:kafka/annotation-error-handling.adoc#dlpr-headers[Managing Dead Letter Record Headers]
        *** xref:retrytopic/retry-config.adoc#retry-topic-global-settings[Configuring Global Settings and Features]

* Kafka headers
    ** can contain MULTIPLE values

[[custom-dlpr]]
== Custom DeadLetterPublishingRecoverer

* you can customize the default `DeadLetterPublishingRecoverer` instances / created by the framework
    ** see xref:retrytopic/features.adoc#retry-headers[Failure Header Management]
    ** | SOME use cases, you need subclass the `DeadLetterPublishingRecoverer`
        *** _Example:_ override `createProducerRecord()` / modify the contents -- sent to the -- retry (or dead-letter) topics

* | v3.0.9,
    ** if you want to create a `DeadLetterPublisherCreator` instance -> override the `RetryConfigurationSupport.configureDeadLetterPublishingContainerFactory
()`
        *** recommendations
            **** use the provided resolvers | constructing the custom instance
        *** _Example:_
+
[source, java]
----
@Override
protected Consumer<DeadLetterPublishingRecovererFactory> 
        configureDeadLetterPublishingContainerFactory() {
    
    return (factory) -> factory.setDeadLetterPublisherCreator(
            (templateResolver, destinationResolver) ->
                    new CustomDLPR(templateResolver, destinationResolver));
}
----

[[exc-based-custom-dlt-routing]]
== Route messages -- based on thrown exceptions, to -- custom DLTs

* | v3.2.0,
    ** ðŸ‘€you can route messages -- ,based on the type of the exception, to -- custom DLTs ðŸ‘€
        *** requirements: specify the routing
        *** rules / followed == rules / followed by xref:retrytopic/features.adoc#topics-autocreation[Topics AutoCreation]
        *** _Examples of configuring:_
            **** _Example1:_ via annotations
+
[source, java]
----
@RetryableTopic(exceptionBasedDltRouting = {
    @ExceptionBasedDltDestination(
        suffix = "-deserialization", exceptions = {DeserializationException.class}  // -> `my-annotated-topic-deserialization-dlt`
    )}
)
@KafkaListener(topics = "my-annotated-topic")
public void processMessage(MyPojo message) {
    // ... message processing
}
----

            **** _Example2:_ via `RetryTopicConfiguration` beans
+
[source, java]
----
@Bean
public RetryTopicConfiguration myRetryTopic(KafkaTemplate<String, MyPojo> template) {
    return RetryTopicConfigurationBuilder
            .newInstance()
            .dltRoutingRules(Map.of("-deserialization", Set.of(DeserializationException.class)))
            .create(kafkaOperations)
            .create(template);
}
----

* Routing customization
    ** == specify additional destinations

* Destinations == `suffix` & `exceptions`
    ** `suffix` -- is used to identify the -- custom DLT
        *** ðŸ‘€if NO match found -> message -- is routed to the -- general purpose DLT ðŸ‘€
