[[how-the-pattern-works]]
= How the Pattern Works

* if message processing fails -> message -- is forwarded to a -- retry topic / back off timestamp
    ** ðŸ’¡spring-kafka framework takes care of
        *** creating the retry topics
        *** set up & configuring the listeners ðŸ’¡
* retry topic consumer -- checks the -- timestamp
    ** ðŸ‘€if it's not YET time to process it (== too early YET) -> consumption for that topic's partition is paused ðŸ‘€
    ** ðŸ‘€if it's to process -> partition consumption is RESUMED -> message is consumed AGAIN ðŸ‘€
        *** if the message processing fails AGAIN ->
            **** message -- will be forwarded to the -- NEXT retry topic
            **** this pattern is repeated UNTIL
                ***** successful processing occurs or
                ***** ðŸ‘€attempts are exhausted & if Dead Letter Topic is configured -> message -- is sent to the -- Dead Letter Topic ðŸ‘€
    ** _Example:_ if you have a "main-topic" topic & want to set up non-blocking retry / exponential backoff of 1000ms + multiplier of [2, 4] attempts -> create the
        *** main-topic-retry-1000 topic + ðŸ‘€related-consumer group ðŸ‘€
        *** main-topic-retry-2000 topic + ðŸ‘€related-consumer group ðŸ‘€
        *** main-topic-retry-4000 topic + ðŸ‘€related-consumer group ðŸ‘€
        *** main-topic-dlt topic + ðŸ‘€related-consumer group ðŸ‘€

* âš ï¸retry mechanism / MULTIPLE retry topics -> Kafka's ordering | that topic, NOT guaranteed âš ï¸

* modes
    ** `RECORD`
        *** suggested
    ** `AckMode`
        *** recommended
        *** + `asyncAcks=true` -> `DefaultErrorHandler` MUST be configured with `seekAfterError=false` ðŸ‘€
            **** | v2.9.10, v3.0.8, `seekAfterError=false` UNCONDITIONALLY
            **** | v2.9.10-,  -> NECESSARY
+
[source, java]
----
@Override
protected void configureCustomizers(CustomizersConfigurer customizersConfigurer) {
    customizersConfigurer.customizeErrorHandler(eh -> eh.setSeekAfterError(false));
}
----
        *** | before PREVIOUS versions, use the default (logging) DLT handler -- NOT compatible with -- any kind of manual `AckMode`
