[[retry-topic-combine-blocking]]
= Combining Blocking and Non-Blocking Retries

* | v2.8.4
    ** ðŸ‘€you can use blocking + non-blocking retries | SAME time ðŸ‘€
        *** + see xref:retrytopic/retry-config.adoc#retry-topic-global-settings[Global Retryable topics]
        *** possible combinations
                **** trigger BOTH retries
                **** trigger 1 kind of retries
                **** go straight to the DLT / WITHOUT retries
        *** ðŸ‘€blocking retries is allowlist (== exceptions / you want to retry)ðŸ‘€
        *** ðŸ‘€non-blocking retries is denylist (== exceptions / NOT want to do non-blocking retries == âš ï¸send directly -- to the -- DLTâš ï¸) ðŸ‘€
        *** _Example:_
+
[source, java]
----
// `ShouldRetryOnlyBlockingException.class` would retry ONLY via blocking. if ALL retries fail -> would go straight to the DLT
// `ShouldRetryViaBothException.class` would retry via blocking. if ALL blocking retries fail -> would be -- forwarded to the -- NEXT retry topic for another set of attempts
@Override
protected void configureBlockingRetries(BlockingRetriesConfigurer blockingRetries) {
    blockingRetries
            .retryOn(ShouldRetryOnlyBlockingException.class, ShouldRetryViaBothException.class)
            .backOff(new FixedBackOff(50, 3));
}

// `ShouldSkipBothRetriesException.class` would NEVER be retried.  if the first processing attempt fails -> would go straight to the DLT
@Override
protected void manageNonBlockingFatalExceptions(List<Class<? extends Throwable>> nonBlockingFatalExceptions) {
    nonBlockingFatalExceptions.add(ShouldSkipBothRetriesException.class);
}

----

* if you want to configure ONLY blocking retries ->
    ** override `configureBlockingRetries` | `@Configuration` class / extends `RetryTopicConfigurationSupport` &
    ** add the exceptions / you want to retry + `BackOff`
        *** default `BackOff` == `FixedBackOff` / NO delay & 9 attempts -- see xref:retrytopic/retry-config.adoc#retry-topic-global-settings[Configuring Global Settings and Features] --
    ** _Example:_
+
[source, java]
----

@Override
protected void configureBlockingRetries(BlockingRetriesConfigurer blockingRetries) {
    blockingRetries
            .retryOn(MyBlockingRetryException.class, MyOtherBlockingRetryException.class)
            .backOff(new FixedBackOff(3_000, 5));
}

----
