[[topic-naming]]
= Topic Naming

* ðŸ‘€Retry topics & DLT naming == mainTopicName + providedOrDefaultValue + delay or index / that topic ðŸ‘€
    ** providedOrDefaultValue
        *** default values are: `retry` or `-dlt`
        *** xref:retrytopic/topic-naming.adoc#retry-topics-and-dlt-suffixes[provide]
    ** delay or index / that topic
        *** default behaviour
            **** | fixed delay configurations / MULTIPLE topics, topic's index
            **** | REST of case, delay values
    ** Reason: ðŸ§  default behavior, create separate retry topics / EACH attempt -> # of retry topics == `maxAttempts` - 1 ðŸ§ 
    ** _Example:_
        *** "my-topic" -> "my-topic-retry-0", "my-topic-retry-1", ..., "my-topic-dlt"
        *** "my-other-topic" -> "my-topic-myRetrySuffix-1000", "my-topic-myRetrySuffix-2000", ..., "my-topic-myDltSuffix"

[[retry-topics-and-dlt-suffixes]]
== Retry Topics and DLT Suffixes

* configure the suffixes / used by the retry & DLT topics
    ** _Example:_
+
[source, java]
----
@RetryableTopic(retryTopicSuffix = "-my-retry-suffix", dltTopicSuffix = "-my-dlt-suffix")
@KafkaListener(topics = "my-annotated-topic")
public void processMessage(MyPojo message) {
    // ... message processing
}
----

[source, java]
----
@Bean
public RetryTopicConfiguration myRetryTopic(KafkaTemplate<String, MyOtherPojo> template) {
    return RetryTopicConfigurationBuilder
            .newInstance()
            .retryTopicSuffix("-my-retry-suffix")
            .dltTopicSuffix("-my-dlt-suffix")
            .create(template);
}
----

[[append-index-or-delay]]
== Appending the Topic's Index or Delay

* specify to append the topic's index or delay values
    ** _Example:_
+
[source, java]
----
@RetryableTopic(topicSuffixingStrategy = TopicSuffixingStrategy.SUFFIX_WITH_INDEX_VALUE)
@KafkaListener(topics = "my-annotated-topic")
public void processMessage(MyPojo message) {
    // ... message processing
}
----

[source, java]
----
@Bean
public RetryTopicConfiguration myRetryTopic(KafkaTemplate<String, MyPojo> template) {
    return RetryTopicConfigurationBuilder
            .newInstance()
            .suffixTopicsWithIndexValues()
            .create(template);
    }
----

[[single-topic-fixed-delay]]
== 1! Topic | Fixed Delay Retries

* if you're using fixed delay policies (_Example:_ `FixedBackOffPolicy` or `NoBackOffPolicy`) & non-blocking retries -> ðŸ‘€ you can use 1! topic to accomplish / ðŸ‘€
    ** naming = mainTopicName + providedOrDefaultValue
        *** == NOT have either the index or the delay values appended

* `FixedDelayStrategy`
    ** NOW deprecated -- & replaced by -- `SameIntervalTopicReuseStrategy`
        *** _Example:_
+
[source, java]
----
@RetryableTopic(backoff = @Backoff(2_000), fixedDelayTopicStrategy = FixedDelayStrategy.SINGLE_TOPIC)
@KafkaListener(topics = "my-annotated-topic")
public void processMessage(MyPojo message) {
    // ... message processing
}
----
+
[source, java]
----
@Bean
public RetryTopicConfiguration myRetryTopic(KafkaTemplate<String, MyPojo> template) {
    return RetryTopicConfigurationBuilder
            .newInstance()
            .fixedBackOff(3_000)
            .maxAttempts(5)
            .useSingleTopicForFixedDelays()
            .create(template);
}
----

[[single-topic-maxinterval-delay]]
== 1! Topic | maxInterval Exponential Delay

* if you're using exponential backoff policy (`ExponentialBackOffPolicy`) & non-blocking retries / delays using configured `maxInterval` -> you can use 1! retry topic /
    ** naming == mainTopicName + providedOrDefaultValue + index or the `maxInterval` value appended
        *** _Example:_

* | v3.2,
    ** default behavior == reuse the retry topic | SAME
    ** if you use exponential backoff ->
        *** retry topics naming == mainTopicName + delay values
            **** âš ï¸if `maxInterval` delay is reached -> MULTIPLE topics created / âš ï¸
                ***** SAME delay
                ***** naming == mainTopicName + delay values + index
                ***** _Example:_
                    ****** -retry-1000
                    ****** -retry-2000
                    ****** -retry-4000
                    ****** -retry-8000
                    ****** -retry-16000-0
                    ****** -retry-16000-1
                    ****** -retry-16000-2
                    ****** ...
                    ****** -retry-16000-224
        *** _Example:_ exponential backoff / `initialInterval=1_000` + `multiplier=2` + `maxInterval=16_000` ->
            **** if you want to keep trying | 1 hour -> you need to configure `maxAttempts=229`
            **** by default, needed retry topics would be
                ***** -retry-1000
                ***** -retry-2000
                ***** -retry-4000
                ***** -retry-8000
                ***** -retry-16000
        *** _Example2:_ exponential backoff / # of retry topics = `maxAttempts-1` -> last retry topic (corresponding to the `maxInterval` delay) being suffixed with an additional index would be:

* if MULTIPLE topics are required -> set `sameIntervalTopicReuseStrategy = SameIntervalTopicReuseStrategy.MULTIPLE_TOPICS`
    ** _Example:_
+
[source, java]
----
@RetryableTopic(attempts = 230,
    backoff = @Backoff(delay = 1_000, multiplier = 2, maxDelay = 16_000),
    sameIntervalTopicReuseStrategy = SameIntervalTopicReuseStrategy.MULTIPLE_TOPICS)
@KafkaListener(topics = "my-annotated-topic")
public void processMessage(MyPojo message) {
    // ... message processing
}
----
+
[source, java]
----
@Bean
public RetryTopicConfiguration myRetryTopic(KafkaTemplate<String, MyPojo> template) {
    return RetryTopicConfigurationBuilder
            .newInstance()            
            .exponentialBackoff(1_000, 2, 16_000)
            .maxAttempts(230)
            .useSingleTopicForSameIntervals()
            .create(template);
}
----

[[custom-naming-strategies]]
== Custom Naming Strategies

* ðŸ‘€if you want custom naming strategies -> register a bean / implements `RetryTopicNamesProviderFactory` ðŸ‘€
    ** _Example:_ adds a prefix to retry/dlt topics names
+
[source, java]
----
@Override
protected RetryTopicComponentFactory createComponentFactory() {
    return new RetryTopicComponentFactory() {
        @Override
        public RetryTopicNamesProviderFactory retryTopicNamesProviderFactory() {
            return new CustomRetryTopicNamesProviderFactory();
        }
    };
}
----
+
[source, java]
----
public class CustomRetryTopicNamesProviderFactory implements RetryTopicNamesProviderFactory {

    @Override
    public RetryTopicNamesProvider createRetryTopicNamesProvider(
                DestinationTopic.Properties properties) {

        if (properties.isMainEndpoint()) {
            return new SuffixingRetryTopicNamesProvider(properties);
        }
        else {
            return new SuffixingRetryTopicNamesProvider(properties) {

                @Override
                public String getTopicName(String topic) {
                    return "my-prefix-" + super.getTopicName(topic);
                }

            };
        }
    }

}
----

* `SuffixingRetryTopicNamesProviderFactory`
    ** == default implementation
