services:
  zookeeper:
    image: lensesio/fast-data-dev:3.6
    container_name: direct-fast-data-dev
    environment:
      SAMPLEDATA: 0
      RUNTESTS: 0
      ADV_HOST: 127.0.0.1
      CONNECT_HEAP: 1G
      CONNECTORS: elastic
    ports:
      - "2181:2181"
      - "9092:9092"
      - "3030:3030"
      - "8081-8083:8081-8083"
      - "9581-9585:9581-9585"